CREATE TABLE SALES_AGENTS (
  AGENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  AGENT_NAME VARCHAR(255) NOT NULL,
  DEPARTMENT_ID VARCHAR(255) NOT NULL
);

CREATE TABLE SALES_RECORDS (
  SALES_RECORD_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  AGENT_ID VARCHAR(255) NOT NULL,
  AMOUNT VARCHAR(255) NOT NULL
);

CREATE TABLE DEPARTMENTS (
  DEPARTMENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
  DEPARTMENT_NAME VARCHAR(255) NOT NULL
);

INSERT INTO SALES_AGENTS VALUES
  (1, "Frank Jones", 1),
  (2, "Sally Smith", 1),
  (3, "Ed Kramer", 2),
  (4, "Susan Johnson", 3);

INSERT INTO SALES_RECORDS VALUES
  (1, 1, 1500),
  (2, 3, 1700),
  (3, 4, 2000),
  (4, 1, 1000),
  (5, 2, 2200);

INSERT INTO DEPARTMENTS VALUES
  (1, "North America"),
  (2, "Europe"),
  (3, "Asia");
